### ISSUE TITLE
OS support? 

### ISSUE THREAD

**Issue by ModischFabrications** [dastoori/higgs#2]
I noticed no OS definition in your Readme, can I assume it works both for Unix and windows? 

I'm aware that I could test it, but this will probably be reoccurring.

**Comment by ModischFabrications** [comment]
Oh, looking through the files it becomes pretty obvious that both should work. You still might want to add it to the readme, ideally with a rough outline which distros are tested.

**Comment by dastoori** [comment]
I put the unix and windows test badges on readme file, I taught that it was enough. 🤔

Thanks for the suggestion, I will add those information later on.

**Comment by ModischFabrications** [comment]
Oh wow, you are right. Totally didn't spot that, feel free to close this issue.
